package com.koala.model;

public class FinanceProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.raw_url
     *
     * @mbggenerated
     */
    private String rawUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.invest_cycle
     *
     * @mbggenerated
     */
    private Integer investCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.risk_score
     *
     * @mbggenerated
     */
    private Integer riskScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.lowest_amount
     *
     * @mbggenerated
     */
    private Integer lowestAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.finance_productcol1
     *
     * @mbggenerated
     */
    private String financeProductcol1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.expected_profit_rate
     *
     * @mbggenerated
     */
    private Float expectedProfitRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.expected_profit_name
     *
     * @mbggenerated
     */
    private String expectedProfitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.invest_field
     *
     * @mbggenerated
     */
    private String investField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.product_type_label
     *
     * @mbggenerated
     */
    private String productTypeLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.channel_name_short
     *
     * @mbggenerated
     */
    private String channelNameShort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.channel_name
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_product.channel_url
     *
     * @mbggenerated
     */
    private String channelUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.id
     *
     * @return the value of finance_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.id
     *
     * @param id the value for finance_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.name
     *
     * @return the value of finance_product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.name
     *
     * @param name the value for finance_product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.source
     *
     * @return the value of finance_product.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.source
     *
     * @param source the value for finance_product.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.raw_url
     *
     * @return the value of finance_product.raw_url
     *
     * @mbggenerated
     */
    public String getRawUrl() {
        return rawUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.raw_url
     *
     * @param rawUrl the value for finance_product.raw_url
     *
     * @mbggenerated
     */
    public void setRawUrl(String rawUrl) {
        this.rawUrl = rawUrl == null ? null : rawUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.invest_cycle
     *
     * @return the value of finance_product.invest_cycle
     *
     * @mbggenerated
     */
    public Integer getInvestCycle() {
        return investCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.invest_cycle
     *
     * @param investCycle the value for finance_product.invest_cycle
     *
     * @mbggenerated
     */
    public void setInvestCycle(Integer investCycle) {
        this.investCycle = investCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.risk_score
     *
     * @return the value of finance_product.risk_score
     *
     * @mbggenerated
     */
    public Integer getRiskScore() {
        return riskScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.risk_score
     *
     * @param riskScore the value for finance_product.risk_score
     *
     * @mbggenerated
     */
    public void setRiskScore(Integer riskScore) {
        this.riskScore = riskScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.lowest_amount
     *
     * @return the value of finance_product.lowest_amount
     *
     * @mbggenerated
     */
    public Integer getLowestAmount() {
        return lowestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.lowest_amount
     *
     * @param lowestAmount the value for finance_product.lowest_amount
     *
     * @mbggenerated
     */
    public void setLowestAmount(Integer lowestAmount) {
        this.lowestAmount = lowestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.finance_productcol1
     *
     * @return the value of finance_product.finance_productcol1
     *
     * @mbggenerated
     */
    public String getFinanceProductcol1() {
        return financeProductcol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.finance_productcol1
     *
     * @param financeProductcol1 the value for finance_product.finance_productcol1
     *
     * @mbggenerated
     */
    public void setFinanceProductcol1(String financeProductcol1) {
        this.financeProductcol1 = financeProductcol1 == null ? null : financeProductcol1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.expected_profit_rate
     *
     * @return the value of finance_product.expected_profit_rate
     *
     * @mbggenerated
     */
    public Float getExpectedProfitRate() {
        return expectedProfitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.expected_profit_rate
     *
     * @param expectedProfitRate the value for finance_product.expected_profit_rate
     *
     * @mbggenerated
     */
    public void setExpectedProfitRate(Float expectedProfitRate) {
        this.expectedProfitRate = expectedProfitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.expected_profit_name
     *
     * @return the value of finance_product.expected_profit_name
     *
     * @mbggenerated
     */
    public String getExpectedProfitName() {
        return expectedProfitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.expected_profit_name
     *
     * @param expectedProfitName the value for finance_product.expected_profit_name
     *
     * @mbggenerated
     */
    public void setExpectedProfitName(String expectedProfitName) {
        this.expectedProfitName = expectedProfitName == null ? null : expectedProfitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.invest_field
     *
     * @return the value of finance_product.invest_field
     *
     * @mbggenerated
     */
    public String getInvestField() {
        return investField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.invest_field
     *
     * @param investField the value for finance_product.invest_field
     *
     * @mbggenerated
     */
    public void setInvestField(String investField) {
        this.investField = investField == null ? null : investField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.product_type_label
     *
     * @return the value of finance_product.product_type_label
     *
     * @mbggenerated
     */
    public String getProductTypeLabel() {
        return productTypeLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.product_type_label
     *
     * @param productTypeLabel the value for finance_product.product_type_label
     *
     * @mbggenerated
     */
    public void setProductTypeLabel(String productTypeLabel) {
        this.productTypeLabel = productTypeLabel == null ? null : productTypeLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.channel_name_short
     *
     * @return the value of finance_product.channel_name_short
     *
     * @mbggenerated
     */
    public String getChannelNameShort() {
        return channelNameShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.channel_name_short
     *
     * @param channelNameShort the value for finance_product.channel_name_short
     *
     * @mbggenerated
     */
    public void setChannelNameShort(String channelNameShort) {
        this.channelNameShort = channelNameShort == null ? null : channelNameShort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.channel_name
     *
     * @return the value of finance_product.channel_name
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.channel_name
     *
     * @param channelName the value for finance_product.channel_name
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_product.channel_url
     *
     * @return the value of finance_product.channel_url
     *
     * @mbggenerated
     */
    public String getChannelUrl() {
        return channelUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_product.channel_url
     *
     * @param channelUrl the value for finance_product.channel_url
     *
     * @mbggenerated
     */
    public void setChannelUrl(String channelUrl) {
        this.channelUrl = channelUrl == null ? null : channelUrl.trim();
    }
}