package com.koala.model;

import java.util.ArrayList;
import java.util.List;

public class FinanceProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    public FinanceProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andRawUrlIsNull() {
            addCriterion("raw_url is null");
            return (Criteria) this;
        }

        public Criteria andRawUrlIsNotNull() {
            addCriterion("raw_url is not null");
            return (Criteria) this;
        }

        public Criteria andRawUrlEqualTo(String value) {
            addCriterion("raw_url =", value, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andRawUrlNotEqualTo(String value) {
            addCriterion("raw_url <>", value, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andRawUrlGreaterThan(String value) {
            addCriterion("raw_url >", value, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andRawUrlGreaterThanOrEqualTo(String value) {
            addCriterion("raw_url >=", value, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andRawUrlLessThan(String value) {
            addCriterion("raw_url <", value, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andRawUrlLessThanOrEqualTo(String value) {
            addCriterion("raw_url <=", value, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andRawUrlLike(String value) {
            addCriterion("raw_url like", value, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andRawUrlNotLike(String value) {
            addCriterion("raw_url not like", value, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andRawUrlIn(List<String> values) {
            addCriterion("raw_url in", values, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andRawUrlNotIn(List<String> values) {
            addCriterion("raw_url not in", values, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andRawUrlBetween(String value1, String value2) {
            addCriterion("raw_url between", value1, value2, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andRawUrlNotBetween(String value1, String value2) {
            addCriterion("raw_url not between", value1, value2, "rawUrl");
            return (Criteria) this;
        }

        public Criteria andInvestCycleIsNull() {
            addCriterion("invest_cycle is null");
            return (Criteria) this;
        }

        public Criteria andInvestCycleIsNotNull() {
            addCriterion("invest_cycle is not null");
            return (Criteria) this;
        }

        public Criteria andInvestCycleEqualTo(Integer value) {
            addCriterion("invest_cycle =", value, "investCycle");
            return (Criteria) this;
        }

        public Criteria andInvestCycleNotEqualTo(Integer value) {
            addCriterion("invest_cycle <>", value, "investCycle");
            return (Criteria) this;
        }

        public Criteria andInvestCycleGreaterThan(Integer value) {
            addCriterion("invest_cycle >", value, "investCycle");
            return (Criteria) this;
        }

        public Criteria andInvestCycleGreaterThanOrEqualTo(Integer value) {
            addCriterion("invest_cycle >=", value, "investCycle");
            return (Criteria) this;
        }

        public Criteria andInvestCycleLessThan(Integer value) {
            addCriterion("invest_cycle <", value, "investCycle");
            return (Criteria) this;
        }

        public Criteria andInvestCycleLessThanOrEqualTo(Integer value) {
            addCriterion("invest_cycle <=", value, "investCycle");
            return (Criteria) this;
        }

        public Criteria andInvestCycleIn(List<Integer> values) {
            addCriterion("invest_cycle in", values, "investCycle");
            return (Criteria) this;
        }

        public Criteria andInvestCycleNotIn(List<Integer> values) {
            addCriterion("invest_cycle not in", values, "investCycle");
            return (Criteria) this;
        }

        public Criteria andInvestCycleBetween(Integer value1, Integer value2) {
            addCriterion("invest_cycle between", value1, value2, "investCycle");
            return (Criteria) this;
        }

        public Criteria andInvestCycleNotBetween(Integer value1, Integer value2) {
            addCriterion("invest_cycle not between", value1, value2, "investCycle");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIsNull() {
            addCriterion("risk_score is null");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIsNotNull() {
            addCriterion("risk_score is not null");
            return (Criteria) this;
        }

        public Criteria andRiskScoreEqualTo(Integer value) {
            addCriterion("risk_score =", value, "riskScore");
            return (Criteria) this;
        }

        public Criteria andRiskScoreNotEqualTo(Integer value) {
            addCriterion("risk_score <>", value, "riskScore");
            return (Criteria) this;
        }

        public Criteria andRiskScoreGreaterThan(Integer value) {
            addCriterion("risk_score >", value, "riskScore");
            return (Criteria) this;
        }

        public Criteria andRiskScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("risk_score >=", value, "riskScore");
            return (Criteria) this;
        }

        public Criteria andRiskScoreLessThan(Integer value) {
            addCriterion("risk_score <", value, "riskScore");
            return (Criteria) this;
        }

        public Criteria andRiskScoreLessThanOrEqualTo(Integer value) {
            addCriterion("risk_score <=", value, "riskScore");
            return (Criteria) this;
        }

        public Criteria andRiskScoreIn(List<Integer> values) {
            addCriterion("risk_score in", values, "riskScore");
            return (Criteria) this;
        }

        public Criteria andRiskScoreNotIn(List<Integer> values) {
            addCriterion("risk_score not in", values, "riskScore");
            return (Criteria) this;
        }

        public Criteria andRiskScoreBetween(Integer value1, Integer value2) {
            addCriterion("risk_score between", value1, value2, "riskScore");
            return (Criteria) this;
        }

        public Criteria andRiskScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("risk_score not between", value1, value2, "riskScore");
            return (Criteria) this;
        }

        public Criteria andLowestAmountIsNull() {
            addCriterion("lowest_amount is null");
            return (Criteria) this;
        }

        public Criteria andLowestAmountIsNotNull() {
            addCriterion("lowest_amount is not null");
            return (Criteria) this;
        }

        public Criteria andLowestAmountEqualTo(Integer value) {
            addCriterion("lowest_amount =", value, "lowestAmount");
            return (Criteria) this;
        }

        public Criteria andLowestAmountNotEqualTo(Integer value) {
            addCriterion("lowest_amount <>", value, "lowestAmount");
            return (Criteria) this;
        }

        public Criteria andLowestAmountGreaterThan(Integer value) {
            addCriterion("lowest_amount >", value, "lowestAmount");
            return (Criteria) this;
        }

        public Criteria andLowestAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("lowest_amount >=", value, "lowestAmount");
            return (Criteria) this;
        }

        public Criteria andLowestAmountLessThan(Integer value) {
            addCriterion("lowest_amount <", value, "lowestAmount");
            return (Criteria) this;
        }

        public Criteria andLowestAmountLessThanOrEqualTo(Integer value) {
            addCriterion("lowest_amount <=", value, "lowestAmount");
            return (Criteria) this;
        }

        public Criteria andLowestAmountIn(List<Integer> values) {
            addCriterion("lowest_amount in", values, "lowestAmount");
            return (Criteria) this;
        }

        public Criteria andLowestAmountNotIn(List<Integer> values) {
            addCriterion("lowest_amount not in", values, "lowestAmount");
            return (Criteria) this;
        }

        public Criteria andLowestAmountBetween(Integer value1, Integer value2) {
            addCriterion("lowest_amount between", value1, value2, "lowestAmount");
            return (Criteria) this;
        }

        public Criteria andLowestAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("lowest_amount not between", value1, value2, "lowestAmount");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1IsNull() {
            addCriterion("finance_productcol1 is null");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1IsNotNull() {
            addCriterion("finance_productcol1 is not null");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1EqualTo(String value) {
            addCriterion("finance_productcol1 =", value, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1NotEqualTo(String value) {
            addCriterion("finance_productcol1 <>", value, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1GreaterThan(String value) {
            addCriterion("finance_productcol1 >", value, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1GreaterThanOrEqualTo(String value) {
            addCriterion("finance_productcol1 >=", value, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1LessThan(String value) {
            addCriterion("finance_productcol1 <", value, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1LessThanOrEqualTo(String value) {
            addCriterion("finance_productcol1 <=", value, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1Like(String value) {
            addCriterion("finance_productcol1 like", value, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1NotLike(String value) {
            addCriterion("finance_productcol1 not like", value, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1In(List<String> values) {
            addCriterion("finance_productcol1 in", values, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1NotIn(List<String> values) {
            addCriterion("finance_productcol1 not in", values, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1Between(String value1, String value2) {
            addCriterion("finance_productcol1 between", value1, value2, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andFinanceProductcol1NotBetween(String value1, String value2) {
            addCriterion("finance_productcol1 not between", value1, value2, "financeProductcol1");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateIsNull() {
            addCriterion("expected_profit_rate is null");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateIsNotNull() {
            addCriterion("expected_profit_rate is not null");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateEqualTo(Float value) {
            addCriterion("expected_profit_rate =", value, "expectedProfitRate");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateNotEqualTo(Float value) {
            addCriterion("expected_profit_rate <>", value, "expectedProfitRate");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateGreaterThan(Float value) {
            addCriterion("expected_profit_rate >", value, "expectedProfitRate");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateGreaterThanOrEqualTo(Float value) {
            addCriterion("expected_profit_rate >=", value, "expectedProfitRate");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateLessThan(Float value) {
            addCriterion("expected_profit_rate <", value, "expectedProfitRate");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateLessThanOrEqualTo(Float value) {
            addCriterion("expected_profit_rate <=", value, "expectedProfitRate");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateIn(List<Float> values) {
            addCriterion("expected_profit_rate in", values, "expectedProfitRate");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateNotIn(List<Float> values) {
            addCriterion("expected_profit_rate not in", values, "expectedProfitRate");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateBetween(Float value1, Float value2) {
            addCriterion("expected_profit_rate between", value1, value2, "expectedProfitRate");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitRateNotBetween(Float value1, Float value2) {
            addCriterion("expected_profit_rate not between", value1, value2, "expectedProfitRate");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameIsNull() {
            addCriterion("expected_profit_name is null");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameIsNotNull() {
            addCriterion("expected_profit_name is not null");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameEqualTo(String value) {
            addCriterion("expected_profit_name =", value, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameNotEqualTo(String value) {
            addCriterion("expected_profit_name <>", value, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameGreaterThan(String value) {
            addCriterion("expected_profit_name >", value, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameGreaterThanOrEqualTo(String value) {
            addCriterion("expected_profit_name >=", value, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameLessThan(String value) {
            addCriterion("expected_profit_name <", value, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameLessThanOrEqualTo(String value) {
            addCriterion("expected_profit_name <=", value, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameLike(String value) {
            addCriterion("expected_profit_name like", value, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameNotLike(String value) {
            addCriterion("expected_profit_name not like", value, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameIn(List<String> values) {
            addCriterion("expected_profit_name in", values, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameNotIn(List<String> values) {
            addCriterion("expected_profit_name not in", values, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameBetween(String value1, String value2) {
            addCriterion("expected_profit_name between", value1, value2, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andExpectedProfitNameNotBetween(String value1, String value2) {
            addCriterion("expected_profit_name not between", value1, value2, "expectedProfitName");
            return (Criteria) this;
        }

        public Criteria andInvestFieldIsNull() {
            addCriterion("invest_field is null");
            return (Criteria) this;
        }

        public Criteria andInvestFieldIsNotNull() {
            addCriterion("invest_field is not null");
            return (Criteria) this;
        }

        public Criteria andInvestFieldEqualTo(String value) {
            addCriterion("invest_field =", value, "investField");
            return (Criteria) this;
        }

        public Criteria andInvestFieldNotEqualTo(String value) {
            addCriterion("invest_field <>", value, "investField");
            return (Criteria) this;
        }

        public Criteria andInvestFieldGreaterThan(String value) {
            addCriterion("invest_field >", value, "investField");
            return (Criteria) this;
        }

        public Criteria andInvestFieldGreaterThanOrEqualTo(String value) {
            addCriterion("invest_field >=", value, "investField");
            return (Criteria) this;
        }

        public Criteria andInvestFieldLessThan(String value) {
            addCriterion("invest_field <", value, "investField");
            return (Criteria) this;
        }

        public Criteria andInvestFieldLessThanOrEqualTo(String value) {
            addCriterion("invest_field <=", value, "investField");
            return (Criteria) this;
        }

        public Criteria andInvestFieldLike(String value) {
            addCriterion("invest_field like", value, "investField");
            return (Criteria) this;
        }

        public Criteria andInvestFieldNotLike(String value) {
            addCriterion("invest_field not like", value, "investField");
            return (Criteria) this;
        }

        public Criteria andInvestFieldIn(List<String> values) {
            addCriterion("invest_field in", values, "investField");
            return (Criteria) this;
        }

        public Criteria andInvestFieldNotIn(List<String> values) {
            addCriterion("invest_field not in", values, "investField");
            return (Criteria) this;
        }

        public Criteria andInvestFieldBetween(String value1, String value2) {
            addCriterion("invest_field between", value1, value2, "investField");
            return (Criteria) this;
        }

        public Criteria andInvestFieldNotBetween(String value1, String value2) {
            addCriterion("invest_field not between", value1, value2, "investField");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelIsNull() {
            addCriterion("product_type_label is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelIsNotNull() {
            addCriterion("product_type_label is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelEqualTo(String value) {
            addCriterion("product_type_label =", value, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelNotEqualTo(String value) {
            addCriterion("product_type_label <>", value, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelGreaterThan(String value) {
            addCriterion("product_type_label >", value, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelGreaterThanOrEqualTo(String value) {
            addCriterion("product_type_label >=", value, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelLessThan(String value) {
            addCriterion("product_type_label <", value, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelLessThanOrEqualTo(String value) {
            addCriterion("product_type_label <=", value, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelLike(String value) {
            addCriterion("product_type_label like", value, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelNotLike(String value) {
            addCriterion("product_type_label not like", value, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelIn(List<String> values) {
            addCriterion("product_type_label in", values, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelNotIn(List<String> values) {
            addCriterion("product_type_label not in", values, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelBetween(String value1, String value2) {
            addCriterion("product_type_label between", value1, value2, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andProductTypeLabelNotBetween(String value1, String value2) {
            addCriterion("product_type_label not between", value1, value2, "productTypeLabel");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortIsNull() {
            addCriterion("channel_name_short is null");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortIsNotNull() {
            addCriterion("channel_name_short is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortEqualTo(String value) {
            addCriterion("channel_name_short =", value, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortNotEqualTo(String value) {
            addCriterion("channel_name_short <>", value, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortGreaterThan(String value) {
            addCriterion("channel_name_short >", value, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortGreaterThanOrEqualTo(String value) {
            addCriterion("channel_name_short >=", value, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortLessThan(String value) {
            addCriterion("channel_name_short <", value, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortLessThanOrEqualTo(String value) {
            addCriterion("channel_name_short <=", value, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortLike(String value) {
            addCriterion("channel_name_short like", value, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortNotLike(String value) {
            addCriterion("channel_name_short not like", value, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortIn(List<String> values) {
            addCriterion("channel_name_short in", values, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortNotIn(List<String> values) {
            addCriterion("channel_name_short not in", values, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortBetween(String value1, String value2) {
            addCriterion("channel_name_short between", value1, value2, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameShortNotBetween(String value1, String value2) {
            addCriterion("channel_name_short not between", value1, value2, "channelNameShort");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNull() {
            addCriterion("channel_name is null");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNotNull() {
            addCriterion("channel_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNameEqualTo(String value) {
            addCriterion("channel_name =", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotEqualTo(String value) {
            addCriterion("channel_name <>", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThan(String value) {
            addCriterion("channel_name >", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_name >=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThan(String value) {
            addCriterion("channel_name <", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThanOrEqualTo(String value) {
            addCriterion("channel_name <=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLike(String value) {
            addCriterion("channel_name like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotLike(String value) {
            addCriterion("channel_name not like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameIn(List<String> values) {
            addCriterion("channel_name in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotIn(List<String> values) {
            addCriterion("channel_name not in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameBetween(String value1, String value2) {
            addCriterion("channel_name between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotBetween(String value1, String value2) {
            addCriterion("channel_name not between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelUrlIsNull() {
            addCriterion("channel_url is null");
            return (Criteria) this;
        }

        public Criteria andChannelUrlIsNotNull() {
            addCriterion("channel_url is not null");
            return (Criteria) this;
        }

        public Criteria andChannelUrlEqualTo(String value) {
            addCriterion("channel_url =", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlNotEqualTo(String value) {
            addCriterion("channel_url <>", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlGreaterThan(String value) {
            addCriterion("channel_url >", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlGreaterThanOrEqualTo(String value) {
            addCriterion("channel_url >=", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlLessThan(String value) {
            addCriterion("channel_url <", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlLessThanOrEqualTo(String value) {
            addCriterion("channel_url <=", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlLike(String value) {
            addCriterion("channel_url like", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlNotLike(String value) {
            addCriterion("channel_url not like", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlIn(List<String> values) {
            addCriterion("channel_url in", values, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlNotIn(List<String> values) {
            addCriterion("channel_url not in", values, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlBetween(String value1, String value2) {
            addCriterion("channel_url between", value1, value2, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlNotBetween(String value1, String value2) {
            addCriterion("channel_url not between", value1, value2, "channelUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table finance_product
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table finance_product
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}